---
- src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"

- src: git@github.com:ysatii/vector-role.git
  scm: git
  version: "0.1.0"

- src: git@github.com:ysatii/lighthouse-role.git
  scm: git
  version: "0.1.0"
