clickhouse:
  hosts:
    clickhouse-01:  
      ansible_host: 51.250.37.168
      ansible_connection: ssh
      ansible_user: lamer
      ansible_ssh_private_key_file: ssh_env/id_rsa_insecure_clickhouse-01

vector:
  hosts:
    vector-02:
      ansible_host: 158.160.156.195
      ansible_connection: ssh
      ansible_user: lamer
      ansible_ssh_private_key_file: ssh_env/id_rsa_insecure_vector-02


lighthouse:
  hosts:
    lighthouse-03:
      ansible_host: 158.160.155.61
      ansible_connection: ssh
      ansible_user: lamer
      ansible_ssh_private_key_file: ssh_env/id_rsa_insecure_lighthouse-03
